version: "3"

services:
  redis:
    image: redis

  db:
    image: postgres
    ports:
      - "2345:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  vote:
    image: vote
    ports:
      - "1000:80"
    links:
      - redis

  worker:
    image: worker
    links:
      - redis
      - db

  result:
    image: result
    ports:
      - "1001:80"
    links:
      - db
